spring:
  datasource:
    url: jdbc:mysql://ls-2f83fa6c87cf7eb81f10d22ed5043bce0dd69eee.c6a334v7wlev.ap-northeast-2.rds.amazonaws.com:3306/dbmaster?characterEncoding=UTF-8
    username: dbmasteruser
    password: E$}O%$6t8MF*!Zll#$vVwsBV~:=[8V(j
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    #properties:
      #hibernate:
        # show_sql: true
        # format_sql: true

#logging.level:
  # org.hibernate.SQL: debug
  # org.hibernate.type: trace